# Generated by Django 6.0.5 on 2026-05-29 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', 'Номер должен быть в формате +7XXXXXXXXXX (10 цифр после +7)')], verbose_name='Телефон'),
        ),
    ]
