# Generated by Django 6.0.5 on 2026-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('открыт', 'Открыт'), ('закрыт', 'Закрыт')], default='open', max_length=6, verbose_name='Статус'),
        ),
    ]
